[package]
name = "ekaci"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = {workspace = true}
clap = {workspace = true}
env_logger = {workspace = true}
log = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
shared = { path = "../shared" }

