[package]
name = "ekaci"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
thiserror = { workspace = true }
shared = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
