name: Rust backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - name: Build, Test, and Lint
      run: nix develop --command cargo build --verbose
      working-directory: ./backend
    - name: Run tests
      run: nix develop --command cargo test --verbose
      working-directory: ./backend
    - name: Run Rust Format
      run: nix develop --command cargo fmt --all --check --verbose
      working-directory: ./backend

